version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: master

jobs:
  validate:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: .circleci/foreach-commit.sh 'yarn validate'
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - run: echo 'TODO'
