version: 2

rebase: &rebase
  run: git fetch -u origin master && GIT_SEQUENCE_EDITOR=true GIT_COMMITTER_NAME='Circle CI' GIT_COMMITTER_EMAIL='dev@spendesk.com' git rebase origin/master --interactive --autosquash

workflows:
  version: 2
  ci:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - *rebase
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
