version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - install
      - validate:
          requires:
            - install
      - build:
          requires:
            - validate
          filters: &only_master
            branches:
              only: master
      - publish:
          requires:
            - build
          # context: semantic-release
          filters: *only_master

jobs:
  install:
    docker:
      - image: &default_image circleci/node:10.15
    steps:
      - checkout
      - restore_cache: &restore_yarn_cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache: &save_yarn_cache
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ./.git
          paths:
            - .
  validate:
    docker:
      - image: *default_image
    steps:
      - attach_workspace:
          at: ./.git
      - run: &git_reset git checkout $CIRCLE_BRANCH && git reset --hard $CIRCLE_BRANCH
      - restore_cache: *restore_yarn_cache
      - run_on_each_commit:
          command: yarn install --frozen-lockfile && yarn validate
      - save_cache: *save_yarn_cache
      - store_test_results:
          path: ./.temp/test-reports
      - store_artifacts:
          path: .temp/test-reports/junit/results.xml
          destination: junit-results.xml
      - store_artifacts:
          path: ./temp/test-coverage/lcov.info
          destination: lcov.info
      - store_artifacts:
          path: ./.temp/test-coverage/coverage-final.json
          destination: coverage.json
  build:
    docker:
      - image: *default_image
    steps:
      - attach_workspace:
          at: ./.git
      - run: *git_reset
      - restore_cache: *restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: ./dist
          paths:
            - .
  publish:
    docker:
      - image: *default_image
    steps:
      - attach_workspace:
          at: ./.git
      - run: *git_reset
      - restore_cache: *restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - run: echo TODO
      # - run: yarn semantic-release

commands:
  run_on_each_commit:
    description: 'Run a command on each commit between master and the branch'
    parameters:
      command:
        type: string
    steps:
      - run: ./.circleci/foreach-commit.sh '<<parameters.command>>'
