version: 2.1
workflows:
  version: 2
  ci:
    jobs:
      - validate
      - publish:
          requires:
            - validate
          filters:
            branches:
              only: master
jobs:
  validate:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: .circleci/foreach-commit.sh 'yarn validate'
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - store_test_results:
          path: .temp/test-reports
      - store_artifacts:
          path: .temp/test-reports/junit/results.xml
          destination: junit-results.xml
      - store_artifacts:
          path: .temp/test-coverage/lcov.info
          destination: lcov.info
      - store_artifacts:
          path: .temp/test-coverage/coverage-final.json
          destination: coverage.json
  publish:
    docker:
      - image: circleci/node:10.15
    steps:
      - run: echo 'TODO'
