version: 2
jobs:
  rebase:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - git fetch -u origin master
      - GIT_SEQUENCE_EDITOR=true git rebase origin/master --interactive --autosquash
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
