version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - install
      - validate:
          requires:
            - install
      - build:
          requires:
            - validate
          filters: &only_master
            branches:
              only: master
      - publish:
          requires:
            - build
          context: semantic-release
          filters: *only_master

jobs:
  install:
    docker: &default_docker
      - image: circleci/node:10.15
        environment:
          GIT_COMMITTER_NAME: Circle CI
          GIT_COMMITTER_EMAIL: yacine.hmito@gmail.com
    steps:
      - checkout
      - install_node_modules
      - persist_to_workspace:
          root: ./.git
          paths:
            - .
  validate:
    docker: *default_docker
    steps:
      - reset_to_current_branch
      - restore_node_modules
      - run_on_each_commit:
          command: yarn install --frozen-lockfile && yarn validate
      - store_test_results:
          path: ./.temp/test-reports
      - store_artifacts:
          path: .temp/test-reports/junit/results.xml
          destination: junit-results.xml
      - store_artifacts:
          path: ./temp/test-coverage/lcov.info
          destination: lcov.info
      - store_artifacts:
          path: ./.temp/test-coverage/coverage-final.json
          destination: coverage.json
  build:
    docker: *default_docker
    steps:
      - reset_to_current_branch
      - install_node_modules
      - run: yarn build
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: ./dist
          paths:
            - .
  publish:
    docker: *default_docker
    steps:
      - reset_to_current_branch
      - install_node_modules
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: yarn semantic-release

commands:
  run_on_each_commit:
    description: 'Run a command on each commit between master and $CIRCLE_BRANCH'
    parameters:
      command:
        type: string
    steps:
      - run: ./.circleci/run-on-each-commit.sh '<<parameters.command>>'
  reset_to_current_branch:
    description: 'Moves to $CIRCLE_BRANCH and performs a hard reset'
    steps:
      - attach_workspace:
          at: ./.git
      - run: git checkout $CIRCLE_BRANCH && git reset --hard $CIRCLE_BRANCH
  restore_node_modules:
    description: 'Loads node_modules from the cache'
    steps:
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
  save_node_modules:
    description: 'Saves the current node_modules to the cache'
    steps:
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
  install_node_modules:
    description: 'Installs the yarn dependencies, restoring the node_modules from the cache and saving them'
    steps:
      - restore_node_modules
      - run: yarn install --frozen-lockfile
      - save_node_modules
